id=ai-response-transformer
name=AI Response Transformer
version=${project.version}
description=${project.description}
class=io.gravitee.policy.ai.responsetransformer.AiResponseTransformerPolicy
type=policy
category=ai
